### PR TITLE
This PR address issues #7 and #8

### PR DESCRIPTION
**Pull request by Cypre55**
Here is the commit message.

> Adds caps.py and JSONs.py, Makes paths OS-unspecific, Updates README.md.
> This commit adds two new file, JSONs.py and caps.py. They have been added to let the user,
> add and edit captions as well as use multiple JSON files as the source. The README and
> redins.py have been adjusted accordingly.

I have also left some space in the README for filling in the process for downloading a JSON file.

### CODE REVIEW

**Comment by Cypre55** [comment]
Sorry, There some minor syntax errors. I shall correct in the next commit

**Comment by Cypre55** [comment]
Here is the other commit message.
> Corrects Syntax Error, Fails to deal with Videos

> I have corrected many synatax errors that I have made. Also I have forgotten to modify
> write_meme() in a manner to accomodate multiple JSONs. One small thing I was unable to correct
> is the name of the txt file created by write_meme(). I would come out as "example.json.txt".
> In the 'main', the chdir was done before check for folder, so I changed that.

**Comment by Cypre55** [comment]
I imported moviepy just in case

**Comment by Cypre55** [comment]
#7 and #8

**Comment by prashantsengar** [comment]
@Cypre55 
1. Use better variable names in caps.py
2. You can also update the variable names in the main file.

**Comment by prashantsengar** [comment]
Merging it right now, you can send a new PR after this

**Pull request merged**
