### PR TITLE
adressing issue#1 

### PR DESCRIPTION
**Pull request by Shardul555**

### CODE REVIEW

**Comment by Shardul555** [comment]
I have sent first commit"Add options for uploading images issue #1" by mistake.
please ignore it  and consider  commit "solving issue#1".

**Comment by prashantsengar** [comment]
@Shardul555 Great work! Please change a few things:
1. Use a better way to take input, you can use [this](https://github.com/prashantsengar/get_input)
2. Use a variable name like `user_choice` instead of `x`

**Comment by prashantsengar** [comment]
And make sure you use the latest copy as the code has been updated by a PR

**Comment by Shardul555** [comment]
> @Shardul555 Great work! Please change a few things:
> 
> 1. Use a better way to take input, you can use [this](https://github.com/prashantsengar/get_input)
> 2. Use a variable name like `user_choice` instead of `x`

Thanks @prashantsengar , I have made another commit right now . Please check it and guide me if any mistake is left.

**Comment by Shardul555** [comment]
hey @prashantsengar  Can you please add kwoc tag to this issue.

**Pull request closed without merging**
